title: Elizabeth Wamalwa
email: elizabethwamalwa001@gmail.com
description: >-
  QA Engineer transitioning into cybersecurity and cloud. Documenting my learning journey here.
remote_theme: mmistakes/minimal-mistakes
plugins:
  - jekyll-remote-theme
  - jekyll-paginate
  - jekyll-feed
  - jekyll-sitemap
  - jemoji

markdown: kramdown

include:
  - _pages

permalink: /:title/
paginate: 5
paginate_path: /page:num/

author:
  name   : "Elizabeth Wamalwa"
  avatar : "/assets/images/bio-photo.jpg"
  bio    : "QA Engineer | Cybersecurity Enthusiast | Cloud Learner"
  links:
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/elizabethwamalwa"
    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "https://www.linkedin.com/in/elizabeth-wamalwa"

minimal_mistakes_skin: default
